name: M1
on:
  workflow_run:
    workflows: ["Draft release"]
    types:
      - completed
jobs:
  aarch64-macos:
    if: ${{ github.repository == 'hexops/mach-gpu-dawn' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, macOS, ARM64]
    defaults:
      run:
        shell: "/usr/bin/arch -arch arm64e /bin/bash --noprofile --norc -eo pipefail {0}"
    steps:
      - name: Clean repository submodules
        # See https://github.com/actions/checkout/issues/385
        run: |
          rm -rf $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clone mach-glfw
        run: rm libs/mach-glfw && git clone https://github.com/hexops/mach-glfw libs/mach-glfw
      - name: install (debug)
        run: zig build install -Dtarget=aarch64-macos.12-none
        env:
          AGREE: true
      - name: upload (debug)
        run: |
          ./dev/upload-release.sh
          # HACK: without this we encounter error: StreamTooLong on the next `zig build` below.
          # no clue why.
          rm -rf zig-cache zig-out
        env:
          RELEASE_NAME: aarch64-macos-none_debug
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install (release-fast)
        run: zig build install -Doptimize=ReleaseFast -Dtarget=aarch64-macos.12-none
        env:
          AGREE: true
      - name: upload (release-fast)
        run: ./dev/upload-release.sh
        env:
          RELEASE_NAME: aarch64-macos-none_release-fast
          UPLOAD_HEADERS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
