name: Publish release
on:
  workflow_run:
    workflows: ["CI", "CI M1"]
    types:
      - completed
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Record latest release version
      id: recorded_release_version
      run: echo "::set-output name=commit::$(git rev-parse --short HEAD)"
    # - name: Publish release
    #   run: echo "TODO(build-system): gh CLI has no way to mark draft as published?"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout hexops/mach monorepo
      uses: actions/checkout@v2
      with:
        repository: hexops/mach
    - name: 'gpu/dawn: update hard-coded binary release version'
      env:
        RELEASE_COMMIT: ${{steps.recorded_release_version.outputs.commit}}
      run: |
        sed -i "/binary_version: \[\]const u8 =/c\    binary_version: []const u8 = \"release-$RELEASE_COMMIT\"," ./gpu-dawn/build.zig
    - name: 'gpu/dawn: use latest binary release'
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: main
        folder: '.'
        commit-message: 'gpu-dawn: update to latest binary release'
